name: alphabet
favicon: null
layout_spectrum: 0.12909880420193076
typography_spectrum: 0.5571721703745425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6199293038807809
  lightness: 0.28967233933508396
  saturation: 0.6969507243484259
  rhythmicContrast: 0.0014667604118585587
purpose: []
